apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - embedding-api-deployment.yaml
  - embedding-api-service.yaml
  - vllm-nano-deployment.yaml
  - vllm-nano-service.yaml
  - vllm-large-shim-deployment.yaml
  - vllm-large-shim-service.yaml
  - gateway.yaml
  - httproute.yaml
