apiVersion: v1
kind: Secret
metadata:
  name: embedding-gateway-secrets
  namespace: inference
type: Opaque
stringData:
  LOCAL_API_KEYS='["local-dev-key"]'
  HUGGING_FACE_HUB_TOKEN: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: vllm-secrets
  namespace: inference
type: Opaque
stringData:
  HUGGING_FACE_HUB_TOKEN: ""
