apiVersion: v1
kind: Service
metadata:
  name: embedding-query-batch-worker-metrics
  namespace: inference
spec:
  type: ClusterIP
  selector:
    app: embedding-query-batch-worker
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
